### ISSUE TITLE
ImportError: No module named 'Crypto'

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [Veil-Framework/Veil#121]
## Veil version
3.1.4

## OS Used - all info (architecture, linux flavor, etc)
Elementary Os ( based on ubuntu )

## How did you install Veil? (Apt, Clone from Github, etc.)
clone

## Did you run the setup script?
yeah

## Pastebin link to error you are encountering (include console actions you took prior to error)
```
~$ ./Veil.py

Traceback (most recent call last):
  File "./Veil.py", line 87, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/home/user/Pentest/Veil/lib/common/orchestra.py", line 23, in __init__
    self.load_tools(cli_stuff)
  File "/home/user/Pentest/Veil/lib/common/orchestra.py", line 67, in load_tools
    command_line_object)
  File "Tools/Evasion/Tool.py", line 41, in __init__
    self.load_payloads(cli_options)
  File "Tools/Evasion/Tool.py", line 242, in load_payloads
    name.replace("/", ".").rstrip('.py'), name)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "Tools/Evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 11, in <module>
    from Tools.Evasion.evasion_common import encryption
  File "/home/user/Pentest/Veil/Tools/Evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
ImportError: No module named 'Crypto'
```
## Any additional info you want to tell me
`pip3 install pycrypto` or `pip3 install crypto` ... didn't resolve the problem 

#### `sudo apt install python3-crypto`

**Comment by modernhacker75** [comment]
i just wrote in terminal "pip install pycrypto" and problem was solved !

**Comment by 4yafes6** [comment]
`pip3 uninstall pycrypto`
`pip3 install pycryptodome`
`python3 Veil.py`

**Comment by alperap** [comment]
Thanks

**Comment by alfalinux** [comment]
> `pip3 uninstall pycrypto` `pip3 install pycryptodome` `python3 Veil.py`

thanks, work for me...

**Comment by Khumoyun1307** [comment]
none of them worked for me

**Comment by Khumoyun1307** [comment]
> `pip3 uninstall pycrypto` `pip3 install pycryptodome` `python3 Veil.py`

same problem even after these commands

**Comment by sonukumar6343** [comment]
thanks it work for me

**Comment by kalitego** [comment]
Thanks...
