### ISSUE TITLE
Unable to create output file: 0009:err:module:import_dll Library pywintypes34.dll 

### ISSUE THREAD

**Issue by xirph** [Veil-Framework/Veil#167]
## Veil version

3.1.4

## OS Used - all info (architecture, linux flavor, etc)

Kali_Linux 2018.1 amd64 (VirtualBox)

## How did you install Veil? (Apt, Clone from Github, etc.)

I cloned it from Github according to the instructions:

```
apt-get -y install git
git clone https://github.com/Veil-Framework/Veil-Evasion.git
cd Veil-Evasion/
cd setup
setup.sh -c
```

## Did you run the setup script?

Yes

## Pastebin link to error you are encountering (include console actions you took prior to error)

I run it:
`./Veil.py`

I choose:
```
use evasion
use python/meterpreter/rev_tcp.py
set LHOST 192.168.0.50
generate
payload2.exe
PyInstaller (1)
```
After that, I get the error:
`[!] ERROR: Unable to create output file.`

When I scroll up the terminal I see more info:

```
0009:err:module:import_dll Library pywintypes34.dll (which is needed by L"C:\\Python34\\lib\\site-packages\\win32\\win32api.pyd") not found
Traceback (most recent call last):
  File "/opt/veil/PyInstaller-3.2.1//pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\depend\bindepend.py", line 38, in <module>
    from ..utils.win32.winmanifest import RT_MANIFEST
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\utils\win32\winmanifest.py", line 97, in <module>
    from PyInstaller.utils.win32 import winresource
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\utils\win32\winresource.py", line 20, in <module>
    import pywintypes
  File "C:\Python34\lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Python34\lib\site-packages\win32\lib\pywintypes.py", line 98, in __import_pywin32_system_module__
    raise ImportError("No system module '%s' (%s)" % (modname, filename))
ImportError: No system module 'pywintypes' (pywintypes34.dll)
```
## Expected behavior

Payload should be created.

## Any additional info you want to tell me

Veil was installed on fresh Kali-Linux-2018.1-vbox-amd64

**Comment by ChrisTruncer** [comment]
The required library didn’t install. Can you run setup.sh with the -c flag?

**Comment by xirph** [comment]
Thank you, it works.

I wrote that I followed the instructions and installed Veil with -c flag, but I checked command history and I did not. My mistake :-)
