### ISSUE TITLE
QUESTIONS WITH PYINSTALL

### ISSUE THREAD

**Issue by ZTR05** [Veil-Framework/Veil#171]
## Veil version
3.14

## OS Used - all info (architecture, linux flavor, etc)
kali 18.1

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone

## Did you run the setup script?
YES

## Pastebin link to error you are encountering (include console actions you took prior to error)
 [>] Please enter the number of your choice: 1
Traceback (most recent call last):
  File "/opt/veil/PyInstaller-3.2.1//pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line 34, in <module>
    from .api import PYZ, EXE, COLLECT, MERGE
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\api.py", line 38, in <module>
    from PyInstaller.utils.win32 import winmanifest, icon, versioninfo, winresource
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\utils\win32\versioninfo.py", line 18, in <module>
    from ...lib import pefile
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\lib\pefile.py", line 26, in <module>
    from past.builtins import cmp, long
ImportError: No module named 'past'

## Expected behavior
please fix it

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
I need more information because Veil is starting fine on my VM.
