### ISSUE TITLE
Please enter the base name for output files (default is payload) Error

### ISSUE THREAD

**Issue by cerkoo** [Veil-Framework/Veil#262]
[>] Please enter the base name for output files (default is payload): cerko
Traceback (most recent call last):
  File "./Veil.py", line 143, in <module>
    the_conductor.main_menu()
  File "/usr/share/veil/lib/common/orchestra.py", line 129, in main_menu
    tool_object.tool_main_menu()
  File "tools/evasion/tool.py", line 370, in tool_main_menu
    self.use_payload(selected_payload_module)
  File "tools/evasion/tool.py", line 403, in use_payload
    if outfile.compiler(selected_payload):
  File "/usr/share/veil/tools/evasion/evasion_common/outfile.py", line 53, in compiler
    with open(source_code_filepath, 'w') as source_file:
PermissionError: [Errno 13] Permission denied: '/var/lib/veil/output/source/cerko.bat'

**Comment by ChrisTruncer** [comment]
That means that you don’t have the proper permissions to write to that directory. Please use an account that has permission to write to that directory, or modify the permissions so your current account can do so.

**Comment by cerkoo** [comment]
thanx ChrisTruncer
I granted permissions but again error

 [>] Please enter the base name for output files (default is payload): cerko
Traceback (most recent call last):
  File "./Veil.py", line 135, in <module>
    the_conductor.main_menu()
  File "/home/cerko/Veil/lib/common/orchestra.py", line 129, in main_menu
    tool_object.tool_main_menu()
  File "tools/evasion/tool.py", line 370, in tool_main_menu
    self.use_payload(selected_payload_module)
  File "tools/evasion/tool.py", line 403, in use_payload
    if outfile.compiler(selected_payload):
  File "/home/cerko/Veil/tools/evasion/evasion_common/outfile.py", line 53, in compiler
    with open(source_code_filepath, 'w') as source_file:
PermissionError: [Errno 13] Permission denied: '/var/lib/veil/output/source/cerko.rc'

**Comment by ChrisTruncer** [comment]
Sorry, but this is still a permissions issue, it states that in the error itself.
