### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by ypdenet** [Veil-Framework/Veil#275]
kali 

[*] Installing (Wine) Python's PIP pefile

Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    0% |▏                               | 8.2kB 8.1MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 491, in _prepare_file
    session=self.session)
  File "C:\Python34\lib\site-packages\pip\download.py", line 825, in unpack_url
    session,
  File "C:\Python34\lib\site-packages\pip\download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "C:\Python34\lib\site-packages\pip\download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "C:\Python34\lib\site-packages\pip\download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "C:\Python34\lib\site-packages\pip\utils\ui.py", line 135, in iter
    self.next(n)
  File "C:\Python34\lib\site-packages\pip\_vendor\progress\__init__.py", line 73, in next
    self.update()
  File "C:\Python34\lib\site-packages\pip\_vendor\progress\bar.py", line 82, in update
    self.writeln(line)
  File "C:\Python34\lib\site-packages\pip\_vendor\progress\helpers.py", line 69, in writeln
    print(line, end='', file=self.file)
  File "C:\Python34\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 136, in write
    self.wrapped.flush()
OSError: [Errno 22] Invalid argument
You are using pip version 7.1.2, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
    0% |▏                               | 8.2kB 8.1MB/s eta 0:00:01Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp936'>
OSError: [Errno 22] Invalid argument
    0% |▏                               | 8.2kB 8.1MB/s eta 0:00:01    0% |▏                               | 8.2kB 8.1MB/s eta 0:00:01 [ERROR] Failed to run (wine) Python pip... Exit code: 2

Collecting future
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
    0% |▏                               | 4.1kB 6.5kB/s eta 0:02:08Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 491, in _prepare_file
    session=self.session)
  File "C:\Python34\lib\site-packages\pip\download.py", line 825, in unpack_url
    session,
  File "C:\Python34\lib\site-packages\pip\download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "C:\Python34\lib\site-packages\pip\download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "C:\Python34\lib\site-packages\pip\download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "C:\Python34\lib\site-packages\pip\utils\ui.py", line 135, in iter
    self.next(n)
  File "C:\Python34\lib\site-packages\pip\_vendor\progress\__init__.py", line 73, in next
    self.update()
  File "C:\Python34\lib\site-packages\pip\_vendor\progress\bar.py", line 82, in update
    self.writeln(line)
  File "C:\Python34\lib\site-packages\pip\_vendor\progress\helpers.py", line 69, in writeln
    print(line, end='', file=self.file)
  File "C:\Python34\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 136, in write
    self.wrapped.flush()
OSError: [Errno 22] Invalid argument
You are using pip version 7.1.2, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
    0% |▏                               | 4.1kB 6.5kB/s eta 0:02:08Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp936'>
OSError: [Errno 22] Invalid argument
    0% |▏                               | 4.1kB 6.5kB/s eta 0:02:08    0% |▏                               | 4.1kB 6.5kB/s eta 0:02:08 [ERROR] Failed to run (wine) Python pip future... Exit code: 2

Collecting pefile
  Downloading https://files.pythonhosted.org/packages/ed/cc/157f20038a80b6a9988abc06c11a4959be8305a0d33b6d21a134127092d4/pefile-2018.8.8.tar.gz (62kB)
    6% |██                              | 4.1kB 18.9MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 491, in _prepare_file
    session=self.session)
  File "C:\Python34\lib\site-packages\pip\download.py", line 825, in unpack_url
    session,
  File "C:\Python34\lib\site-packages\pip\download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "C:\Python34\lib\site-packages\pip\download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "C:\Python34\lib\site-packages\pip\download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "C:\Python34\lib\site-packages\pip\utils\ui.py", line 135, in iter
    self.next(n)
  File "C:\Python34\lib\site-packages\pip\_vendor\progress\__init__.py", line 73, in next
    self.update()
  File "C:\Python34\lib\site-packages\pip\_vendor\progress\bar.py", line 82, in update
    self.writeln(line)
  File "C:\Python34\lib\site-packages\pip\_vendor\progress\helpers.py", line 69, in writeln
    print(line, end='', file=self.file)
  File "C:\Python34\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 136, in write
    self.wrapped.flush()
OSError: [Errno 22] Invalid argument
You are using pip version 7.1.2, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
    6% |██                              | 4.1kB 18.9MB/s eta 0:00:01Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp936'>
OSError: [Errno 22] Invalid argument
    6% |██                              | 4.1kB 18.9MB/s eta 0:00:01    6% |██                              | 4.1kB 18.9MB/s eta 0:00:01 [ERROR] Failed to run (wine) Python pip pefile... Exit code: 2

[ERROR] There was issues installing the following:

 
Failed to run (wine) Python pip... Exit code: 2
Failed to run (wine) Python pip future... Exit code: 2
Failed to run (wine) Python pip pefile... Exit code: 2

 [I] If you have any errors running Veil, run: './Veil.py --setup' and select the nuke the wine folder option

**Comment by ChrisTruncer** [comment]
This doesn’t contain any of the information requested when opening an issue, and is a giant blob of text. Please read the requested information and format of it when submitting an issue.
