### ISSUE TITLE
ImportError: No module named 'pywintypes'

### ISSUE THREAD

**Issue by hoseinamu** [Veil-Framework/Veil#342]
3.1.x

## [?] How would you like to create your payload executable?

     1 - PyInstaller (default)
     2 - Py2Exe

 [>] Please enter the number of your choice: 1
Traceback (most recent call last):
  File "/var/lib/veil/PyInstaller-3.2.1//pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line 32, in <module>
    from ..depend import bindepend
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\depend\bindepend.py", line 38, in <module>
    from ..utils.win32.winmanifest import RT_MANIFEST
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\utils\win32\winmanifest.py", line 97, in <module>
    from PyInstaller.utils.win32 import winresource
  File "Z:\var\lib\veil\PyInstaller-3.2.1\PyInstaller\utils\win32\winresource.py", line 20, in <module>
    import pywintypes
ImportError: No module named 'pywintypes'

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you try running the setup script again? That should be installed if you ran the script

**Comment by ChrisTruncer** [comment]
Closing due to inactivity
