### ISSUE TITLE
./Veil.py running error

### ISSUE THREAD

**Issue by faiyaz207** [Veil-Framework/Veil#345]
After running setup.sh -c successfully, when I try to run ./Veil.py I get the following error:
Traceback (most recent call last):
File "./Veil.py", line 7, in
from lib.common import orchestra
File "/root/github/PayloadsGenerators/Veil/lib/common/orchestra.py", line 10, in
import readline
ImportError: No module named 'readline'## Veil version

## Any additional info you want to tell me

**Comment by ChrisTruncer** [comment]
Can you provide all the information we are asking for?

**Comment by ChrisTruncer** [comment]
Closing due to inactivity
