### ISSUE TITLE
Cannot open Veil

### ISSUE THREAD

**Issue by lazyLaden** [Veil-Framework/Veil#348]
## Did you run the setup script? ./setup.sh 
this is what happened
root@kali:/opt/Veil# python Veil.py 
Traceback (most recent call last):
  File "Veil.py", line 8, in <module>
    from lib.common import helpers
  File "/opt/Veil/lib/common/helpers.py", line 11, in <module>
    import importlib.util
ImportError: No module named util

**Comment by moretii** [comment]
use this command :
`pip install utils`
