### ISSUE TITLE
IndentationError rev_https.py

### ISSUE THREAD

**Issue by ghost** [Veil-Framework/Veil#39]
Receiving an error when compiling python meterpreter/reverse_https.py. 

[?] How would you like to create your payload executable?

     1 - Pyinstaller (default)
     2 - Py2Exe

 [>] Please enter the number of your choice: 1
232 INFO: PyInstaller: 3.2.1
232 INFO: Python: 3.4.4
232 INFO: Platform: Windows-XP-5.1.2600-SP3
234 INFO: wrote Z:\opt\Veil\test4.spec
237 INFO: UPX is not available.
240 INFO: Extending PYTHONPATH with paths
['Z:\\usr\\share\\veil-output\\source', 'Z:\\opt\\Veil']
241 INFO: Will encrypt Python bytecode with key: 0000aPsalNmozPfL
241 INFO: Adding dependencies on pyi_crypto.py module
241 INFO: checking Analysis
242 INFO: Building Analysis because out00-Analysis.toc is non existent
242 INFO: Initializing module dependency graph...
246 INFO: Initializing module graph hooks...
249 INFO: Analyzing base_library.zip ...
2402 INFO: Processing pre-find module path hook   distutils
4085 INFO: Analyzing hidden import 'Crypto.Cipher._AES'
4101 INFO: running Analysis out00-Analysis.toc
4193 INFO: Caching module hooks...
4202 INFO: Analyzing \usr\share\veil-output\source\test4.py
Traceback (most recent call last):
  File "/opt/veil/PyInstaller-3.2.1//pyinstaller.py", line 15, in <module>
    run()
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\building\build_main.py", line 413, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\depend\analysis.py", line 144, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "Z:\opt\veil\PyInstaller-3.2.1\PyInstaller\lib\modulegraph\modulegraph.py", line 1432, in run_script
    co_ast = compile(contents, pathname, 'exec', ast.PyCF_ONLY_AST, True)
  File "Z:\usr\share\veil-output\source\test4.py", line 15
    try:
    ^
IndentationError: unexpected indent

**Comment by ChrisTruncer** [comment]
Please use the formatting that is pre-populated when creating a github issue.

**Comment by ChrisTruncer** [comment]
The fix for this was just merged in. Thanks for the heads up on it!
