### ISSUE TITLE
imports.append("from base64 import b64decode as " + b64var)

### ISSUE THREAD

**Issue by Jasonflo** [Veil-Framework/Veil#416]
## Veil version

<pre><b>Veil</b> | [Version]: 3.1.14
</pre>

## OS Used - all info (architecture, linux flavor, etc)
<pre>PRETTY_NAME=&quot;Kali GNU/Linux Rolling&quot;
NAME=&quot;Kali GNU/Linux&quot;
ID=kali
VERSION=&quot;2021.1&quot;
VERSION_ID=&quot;2021.1&quot;
</pre>

## How did you install Veil? (Apt, Clone from Github, etc.)
try
apt -y install veil
/usr/share/veil/config/setup.sh --force --silent

try
sudo apt-get -y install git
git clone https://github.com/Veil-Framework/Veil.git
cd Veil/
./config/setup.sh --force --silent

try .

/Veil.py --setup 

try
 ./config/setup.sh --force

## Did you run the setup script?

yes

## Any additional info you want to tell me

Veil is a Run. When i executed  command "set USE_POCHERION Y, gives an error message. If i do not execute this command, then everything works.

<pre>[python/meterpreter/rev_https&gt;&gt;]: set USE_PYHERION Y
[python/meterpreter/rev_https&gt;&gt;]: generate
Traceback (most recent call last):
  File &quot;/root/.local/share/Trash/files/Veil.2/./Veil.py&quot;, line 137, in &lt;module&gt;
    the_conductor.main_menu()
  File &quot;/root/.local/share/Trash/files/Veil.2/lib/common/orchestra.py&quot;, line 127, in main_menu
    tool_object.tool_main_menu()
  File &quot;tools/evasion/tool.py&quot;, line 368, in tool_main_menu
    self.use_payload(selected_payload_module)
  File &quot;tools/evasion/tool.py&quot;, line 400, in use_payload
    selected_payload.generate()
  File &quot;tools/evasion/payloads/python/meterpreter/rev_https.py&quot;, line 147, in generate
    payload_code = encryption.pyherion(payload_code)
  File &quot;/root/.local/share/Trash/files/Veil.2/tools/evasion/evasion_common/encryption.py&quot;, line 217, in pyherion
    imports.append(&quot;from base64 import b64decode as &quot; + b64var)
TypeError: can only concatenate str (not &quot;bytes&quot;) to str
</pre>

**Comment by Jasonflo** [comment]
<pre> [*] <font color="#FF8A18"><b>Installing Python&apos;s pycrypto (via apt)...</b></font>

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3-crypto
 <font color="#EC0101"><b>[ERROR] Failed with installing dependencies (6): 0</b></font>
</pre>

**Comment by Jasonflo** [comment]
i update python 3.9.
and error change

[python/meterpreter/rev_https>>]: set USE_PYHERION Y
[python/meterpreter/rev_https>>]: generate
Traceback (most recent call last):
  File "/usr/share/veil/./Veil.py", line 145, in <module>
    the_conductor.main_menu()
  File "/usr/share/veil/lib/common/orchestra.py", line 127, in main_menu
    tool_object.tool_main_menu()
  File "tools/evasion/tool.py", line 368, in tool_main_menu
    self.use_payload(selected_payload_module)
  File "tools/evasion/tool.py", line 400, in use_payload
    selected_payload.generate()
  File "tools/evasion/payloads/python/meterpreter/rev_https.py", line 147, in generate
    payload_code = encryption.pyherion(payload_code)
  File "/usr/share/veil/tools/evasion/evasion_common/encryption.py", line 209, in pyherion
    encrypted_code, key, iv = aes_encryption("\n".join(codebase), encryption_pad='{')
  File "/usr/share/veil/tools/evasion/evasion_common/encryption.py", line 21, in aes_encryption
    aes_cipher_object = AES.new(random_aes_key, AES.MODE_CBC, iv)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/lib/python3/dist-packages/Cryptodome/Cipher/AES.py", line 103, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/usr/lib/python3/dist-packages/Cryptodome/Util/_raw_api.py", line 144, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

**Comment by Jasonflo** [comment]
Please Help .

**Comment by EmilioTM** [comment]
Please i have the same problem. Help.
