### ISSUE TITLE
Traceback (most recent call last):   File "/home/kali/Veil/./Veil.py", line 10, in <module>     from lib.common import orchestra   File "/home/kali/Veil/lib/common/orchestra.py", line 7, in <module>     import readline ModuleNotFoundError: No module named 'readline'

### ISSUE THREAD

**Issue by Ankit9022** [Veil-Framework/Veil#425]
## How did you install Veil? (Apt, Clone from Github, etc.)
GitHub clone

## Did you run the setup script?
Yes

## Any additional info you want to tell me

**Comment by ZodiacSploit** [comment]
me too I have the same problem Note :Python3 and pip are updated veil installation was fine but when I type ./Veil.py it gives me the same error can someone help me

**Comment by PsychologicalBinary** [comment]
Hi, I've run into the same problem, I think.

`└─# ./Veil.py                
Traceback (most recent call last):
  File "/opt/Veil/./Veil.py", line 98, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/opt/Veil/lib/common/orchestra.py", line 29, in __init__
    self.load_tools(cli_stuff)
  File "/opt/Veil/lib/common/orchestra.py", line 75, in load_tools
    self.imported_tools[name] = module.Tools(
  File "tools/evasion/tool.py", line 39, in __init__
    self.load_payloads(cli_options)
  File "tools/evasion/tool.py", line 248, in load_payloads
    module = helpers.load_module(name)
  File "/opt/Veil/lib/common/helpers.py", line 172, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "tools/evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 9, in <module>
    from tools.evasion.evasion_common import encryption
  File "/opt/Veil/tools/evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
ModuleNotFoundError: No module named 'Crypto'
`

**Comment by dkanze** [comment]
I have the same problem.  Was a solution identified?

└─# ./Veil.py Traceback (most recent call last): File "/opt/Veil/./Veil.py", line 98, in <module> the_conductor = orchestra.Conductor(args) File "/opt/Veil/lib/common/orchestra.py", line 29, in __init__ self.load_tools(cli_stuff) File "/opt/Veil/lib/common/orchestra.py", line 75, in load_tools self.imported_tools[name] = module.Tools( File "tools/evasion/tool.py", line 39, in __init__ self.load_payloads(cli_options) File "tools/evasion/tool.py", line 248, in load_payloads module = helpers.load_module(name) File "/opt/Veil/lib/common/helpers.py", line 172, in load_module spec.loader.exec_module(module) File "<frozen importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "tools/evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 9, in <module> from tools.evasion.evasion_common import encryption File "/opt/Veil/tools/evasion/evasion_common/encryption.py", line 8, in <module> from Crypto.Cipher import ARC4 ModuleNotFoundError: No module named 'Crypto'

Thanks
Dan
