### ISSUE TITLE
I am getting this error whenever I try to run veil

### ISSUE THREAD

**Issue by ZodiacSploit** [Veil-Framework/Veil#426]
Traceback (most recent call last):
  File "/opt/Veil/./Veil.py", line 98, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/opt/Veil/lib/common/orchestra.py", line 29, in __init__
    self.load_tools(cli_stuff)
  File "/opt/Veil/lib/common/orchestra.py", line 75, in load_tools
    self.imported_tools[name] = module.Tools(
  File "/opt/Veil/tools/evasion/tool.py", line 39, in __init__
    self.load_payloads(cli_options)
  File "/opt/Veil/tools/evasion/tool.py", line 248, in load_payloads
    module = helpers.load_module(name)
  File "/opt/Veil/lib/common/helpers.py", line 172, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/Veil/tools/evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 9, in <module>
    from tools.evasion.evasion_common import encryption
  File "/opt/Veil/tools/evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
ModuleNotFoundError: No module named 'Crypto'

Can someone Help I have installed it using git 
and I have purged it and re-installed it but same error

my Python and pip are enabled and updated

Any Suggestions guys ? Thanks.

**Comment by nolimitcarter** [comment]
You should just be able to install Crypto via pip. Does that fix it?

**Comment by Smaregg** [comment]
> 
> 
> You should just be able to install Crypto via pip. Does that fix it?

I installed crypto and "pip list" command shows there is a "crypto" pacakge, but still not working. 
However, I went to the "/opt/Veil/tools/evasion/evasion_common/encryption.py" file, changed "Crypto.Cipher" to "crypto.Cipher", the error becomes No module named 'crypto.Cipher'. Does that means this library changed it's name?

**Comment by nolimitcarter** [comment]
No the `crypto` package itself has not been updated in years now. I am assuming you used quotations on "crypto" to show you installed in with a lowercase "c". I would try installing it with `pip install Crypto` since that seems to be what it is looking for. I tried this and it installed. I don't have this problem though and am just giving advice at this point. I wouldn't go in and edit any files unless your sure of something. You also said it it still not working, what error message did it give you if it's not a capitalization error?

**Comment by Smaregg** [comment]
> 
> 
> No the `crypto` package itself has not been updated in years now. I am assuming you used quotations on "crypto" to show you installed in with a lowercase "c". I would try installing it with `pip install Crypto` since that seems to be what it is looking for. I tried this and it installed. I don't have this problem though and am just giving advice at this point. I wouldn't go in and edit any files unless your sure of something. You also said it it still not working, what error message did it give you if it's not a capitalization error?

I tried to install Crypto with capital 'C',  and used 'pip list' to show all the packages, there's only one 'crypto' with lowercase 'c', and my error is the same with OP : No module named 'Crypto'

**Comment by nolimitcarter** [comment]
> > No the `crypto` package itself has not been updated in years now. I am assuming you used quotations on "crypto" to show you installed in with a lowercase "c". I would try installing it with `pip install Crypto` since that seems to be what it is looking for. I tried this and it installed. I don't have this problem though and am just giving advice at this point. I wouldn't go in and edit any files unless your sure of something. You also said it it still not working, what error message did it give you if it's not a capitalization error?
> 
> I tried to install Crypto with capital 'C', and used 'pip list' to show all the packages, there's only one 'crypto' with lowercase 'c', and my error is the same with OP : No module named 'Crypto'

That's strange, I really can't imagine what it would be then. It looks like you are just missing the package but it seems like you're sure you already have it in the first place. In my previous reply I said crypto installs for me with either a capital or lowercase "c", and that is still the case, but when I go into `pip list`, it only shows `crypto` like you said.

**Comment by MrEnergy64** [comment]
RESOLVED with:

pip3 uninstall pycrypto && pip3 install pycryptodome

Thanks


Same issue with Crypto:

Install Crypto via pip3 install Crypto:

pip3 install Crypto                                                      1 ⨯
Collecting Crypto
  Downloading crypto-1.4.1-py2.py3-none-any.whl (18 kB)
Collecting shellescape
  Downloading shellescape-3.8.1-py2.py3-none-any.whl (3.1 kB)
Collecting Naked
  Downloading Naked-0.1.31-py2.py3-none-any.whl (590 kB)
     |████████████████████████████████| 590 kB 3.0 MB/s 
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from Naked->Crypto) (2.25.1)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from Naked->Crypto) (5.4.1)
Installing collected packages: shellescape, Naked, Crypto
Successfully installed Crypto-1.4.1 Naked-0.1.31 shellescape-3.8.1

..then I start ./Veil.py:

./Veil.py          
Traceback (most recent call last):
  File "/root/Downloads/Veil/./Veil.py", line 98, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/root/Downloads/Veil/lib/common/orchestra.py", line 29, in __init__
    self.load_tools(cli_stuff)
  File "/root/Downloads/Veil/lib/common/orchestra.py", line 75, in load_tools
    self.imported_tools[name] = module.Tools(
  File "tools/evasion/tool.py", line 39, in __init__
    self.load_payloads(cli_options)
  File "tools/evasion/tool.py", line 248, in load_payloads
    module = helpers.load_module(name)
  File "/root/Downloads/Veil/lib/common/helpers.py", line 172, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "tools/evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 9, in <module>
    from tools.evasion.evasion_common import encryption
  File "/root/Downloads/Veil/tools/evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
ModuleNotFoundError: No module named 'Crypto'

My system: Linux gedu-kali2.gedu.info 5.14.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux

**Comment by LrdCnCn** [comment]
thank you
