### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by loda26** [Veil-Framework/Veil#457]
I was trying to install Veil on kali Linux on virtualbox, and after I ran these commands

```
sudo apt-get -y install git
git clone https://github.com/Veil-Framework/Veil.git
cd Veil/
./config/setup.sh --force --silent
./Veil.py
```
Veil was supposed to run but this ran insted
```
Traceback (most recent call last):
  File "/root/Veil/./Veil.py", line 98, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/root/Veil/lib/common/orchestra.py", line 29, in __init__
    self.load_tools(cli_stuff)
  File "/root/Veil/lib/common/orchestra.py", line 75, in load_tools
    self.imported_tools[name] = module.Tools(
  File "tools/evasion/tool.py", line 39, in __init__
    self.load_payloads(cli_options)
  File "tools/evasion/tool.py", line 248, in load_payloads
    module = helpers.load_module(name)
  File "/root/Veil/lib/common/helpers.py", line 172, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "tools/evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 9, in <module>
    from tools.evasion.evasion_common import encryption
  File "/root/Veil/tools/evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
ModuleNotFoundError: No module named 'Crypto'
```

**Comment by Lingeshlk** [comment]
I have the same problem. Was a solution identified?

**Comment by Idlefase** [comment]
Veil needs to be installed trough apt because of the kali config/libs etc

This way you will brick your kali install. 

I suggest you read the introduction of kali linux in their docs.

**Comment by P15ARTH** [comment]
pip install pycrypto
and your problem fill solve

**Comment by ghost** [comment]
same problem what to do

**Comment by SYC-00** [comment]
there is a simple commad you have to type;;

pip install pycrypto

and done everything will be fine.

**Comment by jshark-byte** [comment]
Hasnt worked

**Comment by mohammadazeemwani** [comment]
first update the sources by running : `apt-get update`
then upgrade using :`apt-get updgrade`

then install the veil dependencies by : `./setup.sh --silent --force`
the above command the override the existing packages and install the new ones if necessary

now make sure you have Crypo module installed by : `pip install pycrypto`
mostly it should show req. already satisfied

open this file that is showing error by running:
`open /opt/Veil/tools/evasion/evasion_common/encryption.py`

then replace all  `Crypto` with `Cryptodome` because : 
**_In Python, the Crypto library has been deprecated and replaced by the Cryptodome library._**

save the file and run `./Veil.py` in the Veil directory and you should be good to go

**Comment by Badir1942** [comment]
> first update the sources by running : `apt-get update` then upgrade using :`apt-get updgrade`
> 
> then install the veil dependencies by : `./setup.sh --silent --force` the above command the override the existing packages and install the new ones if necessary
> 
> now make sure you have Crypo module installed by : `pip install pycrypto` mostly it should show req. already satisfied
> 
> open this file that is showing error by running: `open /opt/Veil/tools/evasion/evasion_common/encryption.py`
> 
> then replace all `Crypto` with `Cryptodome` because : **_In Python, the Crypto library has been deprecated and replaced by the Cryptodome library._**
> 
> save the file and run `./Veil.py` in the Veil directory and you should be good to go

Thank you bro

**Comment by RedCreator888** [comment]
> first update the sources by running : `apt-get update` then upgrade using :`apt-get updgrade`
> 
> then install the veil dependencies by : `./setup.sh --silent --force` the above command the override the existing packages and install the new ones if necessary
> 
> now make sure you have Crypo module installed by : `pip install pycrypto` mostly it should show req. already satisfied
> 
> open this file that is showing error by running: `open /opt/Veil/tools/evasion/evasion_common/encryption.py`
> 
> then replace all `Crypto` with `Cryptodome` because : **_In Python, the Crypto library has been deprecated and replaced by the Cryptodome library._**
> 
> save the file and run `./Veil.py` in the Veil directory and you should be good to go

Thank you @mohammadazeemwani worked like a charm.

**Comment by mohammadazeemwani** [comment]
Hey fellas just do one thing use this instead: [https://github.com/mohammadazeemwani/Veil](url) instead >> Enjoy.

**Comment by Akshit-K25** [comment]
> first update the sources by running : `apt-get update` then upgrade using :`apt-get updgrade`
> 
> then install the veil dependencies by : `./setup.sh --silent --force` the above command the override the existing packages and install the new ones if necessary
> 
> now make sure you have Crypo module installed by : `pip install pycrypto` mostly it should show req. already satisfied
> 
> open this file that is showing error by running: `open /opt/Veil/tools/evasion/evasion_common/encryption.py`
> 
> then replace all `Crypto` with `Cryptodome` because : **_In Python, the Crypto library has been deprecated and replaced by the Cryptodome library._**
> 
> save the file and run `./Veil.py` in the Veil directory and you should be good to go

I am new, so idk properly for the replcaing part of cryptodome can u tell it in a bit detail.
how do we replace it?

**Comment by mohammadazeemwani** [comment]
> I am new, so idk properly for the replcaing part of cryptodome can u tell it in a bit detail. how do we replace it?

Use the above link I have mentioned https://github.com/Veil-Framework/Veil/issues/url (It works). if you still need explanation, get to me on `mohammadazeemwani@proton.me`
