### ISSUE TITLE
Error in Veil.py code when trying to launch it.

### ISSUE THREAD

**Issue by Molpo456** [Veil-Framework/Veil#488]
## Veil version
Veil 3.1

## OS Used - all info (architecture, linux flavor, etc)
Linux kali 6.0.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.7-1kali1 (2022-11-07) x86_64 GNU/Linux

## How did you install Veil? (Apt, Clone from Github, etc.)
sudo git clone https://github.com/Veil-Framework/Veil.git

## Did you run the setup script?
yes

## Pastebin link to error you are encountering (include console actions you took prior to error)
After running the setup.sh and launching the Veil.py I got the error:

 "veil [!] ERROR #2-3: Can't find the WINE profile for Ruby v1.8.7 (/var/lib/veil/wine//drive_c/Ruby187/bin/ruby.exe). Run: /usr/share/veil/config/setup.sh --force --silent"

I then run "/usr/share/veil/config/setup.sh --force --silent"
and when I try to run the Veil.py again I got the mistakes below:

"Traceback (most recent call last):
  File "/opt/Veil/./Veil.py", line 98, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/opt/Veil/lib/common/orchestra.py", line 29, in __init__
    self.load_tools(cli_stuff)
  File "/opt/Veil/lib/common/orchestra.py", line 75, in load_tools
    self.imported_tools[name] = module.Tools(
  File "/opt/Veil/tools/evasion/tool.py", line 39, in __init__
    self.load_payloads(cli_options)
  File "/opt/Veil/tools/evasion/tool.py", line 248, in load_payloads
    module = helpers.load_module(name)
  File "/opt/Veil/lib/common/helpers.py", line 172, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/Veil/tools/evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 9, in <module>
    from tools.evasion.evasion_common import encryption
  File "/opt/Veil/tools/evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
  File "/home/purplesquid/.local/lib/python3.10/site-packages/Crypto/Cipher/ARC4.py", line 119, in <module>
    key_size = xrange(1,256+1)
NameError: name 'xrange' is not defined. Did you mean: 'range'?"

## Any additional info you want to tell me
I've been trying to change the first line in the python code "#!/usr/bin/env python3"
I tried("#!/usr/bin python3", "#!/usr/bin/env python", "#!/usr/bin/env python2"),
i also tried the chmod +777 for Veil.py but still doesn't work. If anyone has a solution please help me solve this.

**Comment by gouthamkm** [comment]
─# ./Veil.py   
    after executing thisim getting this error please resoleve it
Traceback (most recent call last):
  File "/home/kali/Downloads/Veil/./Veil.py", line 98, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/home/kali/Downloads/Veil/lib/common/orchestra.py", line 29, in __init__
    self.load_tools(cli_stuff)
  File "/home/kali/Downloads/Veil/lib/common/orchestra.py", line 75, in load_tools
    self.imported_tools[name] = module.Tools(
  File "/home/kali/Downloads/Veil/tools/evasion/tool.py", line 39, in __init__
    self.load_payloads(cli_options)
  File "/home/kali/Downloads/Veil/tools/evasion/tool.py", line 248, in load_payloads
    module = helpers.load_module(name)
  File "/home/kali/Downloads/Veil/lib/common/helpers.py", line 172, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kali/Downloads/Veil/tools/evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 9, in <module>
    from tools.evasion.evasion_common import encryption
  File "/home/kali/Downloads/Veil/tools/evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/ARC4.py", line 119, in <module>
    key_size = xrange(1,256+1)
NameError: name 'xrange' is not defined. Did you mean: 'range'?

**Comment by r4jn1k4nt** [comment]
Change **key_size = xrange(1,256+1)** to **key_size = range(1,256+1)** in **/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/ARC4.py**. I hope it works.
