### ISSUE TITLE
Another damn installation issue 

### ISSUE THREAD

**Issue by Rafaelko11** [Veil-Framework/Veil#496]
## Veil version
3.1.14

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2023.1
ARCH64

## How did you install Veil? (Apt, Clone from Github, etc.)
Clone from Github
(Also tried apt but same error)

## Did you run the setup script?
Yes at least 10 times it start to go on my nerves

## Pastebin link to error you are encountering (include console actions you took prior to error)
I'll give you all the error : 
----------------------------------------------------------------------------------------------------------------------------------
Start Error
Traceback (most recent call last):
  File "/opt/Veil/./Veil.py", line 98, in <module>
    the_conductor = orchestra.Conductor(args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Veil/lib/common/orchestra.py", line 29, in __init__
    self.load_tools(cli_stuff)
  File "/opt/Veil/lib/common/orchestra.py", line 75, in load_tools
    self.imported_tools[name] = module.Tools(
                                ^^^^^^^^^^^^^
  File "/opt/Veil/tools/evasion/tool.py", line 39, in __init__
    self.load_payloads(cli_options)
  File "/opt/Veil/tools/evasion/tool.py", line 248, in load_payloads
    module = helpers.load_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Veil/lib/common/helpers.py", line 172, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/Veil/tools/evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 9, in <module>
    from tools.evasion.evasion_common import encryption
  File "/opt/Veil/tools/evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
ModuleNotFoundError: No module named 'Crypto'
----------------------------------------------------------------------------------------------------------------------------------
Setup error
I'll put evrything on this pastbin link bc github don't let me more than 65000 characters :(

https://pastebin.com/piNY2XEb

 (Yeah its very long ...)

## Any additional info you want to tell me
If you need more info just ask me !
I'll be very gratefull if you can just help me a little more :)
Have a good day !

**Comment by b14ckw1d0w** [comment]
pip install pycrypto

**Comment by edabezek** [comment]
in the folder you downloaded, can you try this 

![Ekran Alıntısı](https://github.com/Veil-Framework/Veil/assets/86590339/0c776529-ab40-4790-a50b-e5d3986b0dc3)
